### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by trungvuh** [trungvuh/Doable#2]
[ ] Backend: DB, model, controller, views
[ ] Redux Loop: api_util, actions, reducer
[ ] Presentational Components
[ ] Styling
[ ] Smooth, bug-free navigation
[ ] Adequate and appropriate seeds

**Comment by s-pangburn** [comment]
- [x] On the Sign In page, "New User" should be "New User?"
- [x] More padding between the input fields and buttons on your login/signup forms
- [x] More padding on the bottom of "Where anything is possible. Even a baby can do it"
  + Also, should probably be punctuated here (Even a baby can do it!) Not necessary in the header, but for main page text, use proper punctuation
- [x] Header logo should have at least a little padding on the bottom, or move it up slightly.
- [x] Error messages stretch the form container. Try to set it to a fixed width and have the text wrap. Also, text should probably be a little smaller and a more eye-catching color (like red)
- [x] The background on the login/signup page should not be white, should be slightly darker so that the login form stands out with its white background, if that makes sense?
- [x] Logout button should set CSS for `cursor: pointer;` on hover
- [x] Errors should clear when switching between login/signup.

**Comment by trungvuh** [comment]
All done Stephen!

**Comment by s-pangburn** [comment]
- [x] The beige color doesn't look very professional. I think you should stick to the grey monochrome look you had before.
- [x] "Where anything is possible..." <- still needs more padding on bottom
- [x] Don't make all the text red, just the errors. The text should be gray like it was before.
- [x] The hover effect on the button needs to be faster and less heavy, it's too distracting. Hover effects should be subtle, and the goal is to balance looking nice without distracting the user from what they were originally doing on the site.
- [x] The top of the page says "Log in", but the form says "Sign in". They should use consistent language.

**Comment by trungvuh** [comment]
All done Stephen. I use the background colors of Instructable now, hopefully it looks ok. Let me know what you think. Thanks Stephen!

**Comment by s-pangburn** [comment]
Looks good! 

- [ ] Logging out should take you to the login page

But I think this is good enough to move on! I will close this issue. Good work!
