### ISSUE TITLE
PA Review: Adding photos/videos to Project

### ISSUE THREAD

**Issue by trungvuh** [trungvuh/Doable#5]
[ ] Upload photo for project profile picture
[ ] Adding photo/video to project's description

**Comment by s-pangburn** [comment]
This is copied over from my feedback for projects:

- [x] The image upload dialog should ideally have some indicator of success (even just displaying the state's img_url if successful is okay)
- [x] Your images should keep their dimensions without stretching (I can show you how to do this tomorrow)
- [x] Have the "Create Project" and "Cancel" buttons be the same size as the "Upload a Picture" button. Makes it look more unified.

**Comment by trungvuh** [comment]
All Done. For the buttons, I would like to keep them as their sizes right now, if that's ok. Since the "Create Project" and "Cancel" will also go onto the Project Detail Page, so making them bigger does not suit it really well. Vice versa, making the "Edit/Upload Project Picture" smaller does not quite fit the size of the form that I wanted. Hope that's ok.

**Comment by s-pangburn** [comment]
Sure, I wouldn't call it a dealbreaker. Nicely done! One last thing:

- [ ] The "Upload Successful!" text is clickable and opens the image dialog. This feels a little strange, so please fix it when you have the time. Not critical though!

And because it's not critical, I will go ahead and mark this issue complete :)
